{{ if .Values.sandbox.azure }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: peer-pods-secret-policy
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: azure-peer-pods-creds
      spec:
        remediationAction: enforce
        severity: medium
        object-templates:
        - complianceType: mustonlyhave
          objectDefinition:
            apiVersion: v1
            type: Opaque
            kind: Secret
            metadata:
              name: peer-pods-secret
              namespace: openshift-sandboxed-containers-operator
            data:
              AZURE_CLIENT_ID: '{{ `{{ fromSecret "openshift-cloud-controller-manager" "azure-cloud-credentials" "azure_client_id" }}` }}'
              AZURE_CLIENT_SECRET: '{{ `{{ fromSecret "openshift-cloud-controller-manager" "azure-cloud-credentials" "azure_client_secret" }}` }}'
              AZURE_TENANT_ID: '{{ `{{ fromSecret "openshift-cloud-controller-manager" "azure-cloud-credentials" "azure_tenant_id" }}` }}'
              AZURE_SUBSCRIPTION_ID: '{{ `{{ fromSecret "openshift-cloud-controller-manager" "azure-cloud-credentials" "azure_subscription_id" }}` }}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: peer-pod-secret-binding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
placementRef:
  name: azure-peer-pods-secret-rule
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: peer-pods-secret-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
------
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: azure-peer-pods-secret-rule
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchLabels:
      cloud: Azure
---
{{ end }}