{{ if .Values.sandbox.azure }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: ssh-key-secret-eso
  namespace: openshift-sandboxed-containers-operator
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: ssh-key-secret
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.sandbox.sshKey }}

{{ end }}