{{- if ne .Values.global.secretStore.backend "none" }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata: 
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: kbs-passphrase-eso
  namespace: {{ .Values.kbs.deployNS }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  data:
  target:
    name: passphrase
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.kbs.passphrase }}
{{- end }}