---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata: 
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: tls-cert-eso
  namespace: trustee-operator-system
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: kbs-https-certificate
    template:
      type: Opaque
  data:
    - secretKey: tls.crt
      remoteRef:
        key: 'secret/data/pushsecrets/kbs-tls-self-signed'
        property: certificate


