- name: Retrieve Credentials for AAP on OpenShift
  become: false
  connection: local
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure collection is installed
      community.general.ansible_galaxy_install:
        type: collection
        name: azure.azcollection
    - name: Install a Python package
      ansible.builtin.pip:
        requirements: "~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt"
        extra_args: --user
