name: Ansible Lint # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v4

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint@06f616d6e86e9ce4c74393318d1cbb2d016af413
        # Let's point it to the path